// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbepscombakzdvruuxav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZXBzY29tYmFremR2cnV1eGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODg5OTEsImV4cCI6MjA2Njk2NDk5MX0.vahd7AyhmuJ22EzpapV237jPQPh4UjL-gt6QMvVRozs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});